### ISSUE TITLE
ImportError: cannot import name 'gen_micro_macro_result'

### ISSUE THREAD

**Issue by strayberry** [thunlp/DSDocRE#1]
File "/content/DSDocRE/tools/output_tool.py", line 3, in <module>
    from .accuracy_tool import gen_micro_macro_result
ImportError: cannot import name 'gen_micro_macro_result'

The gen_micro_macro_result function not exists in accuracy_tool.py file.

**Comment by qiunlp** [comment]
同上

**Comment by xcjthu** [comment]
Sorry for missing that. I have updated the code!
