### ISSUE TITLE
论文里面的数据问题

### ISSUE THREAD

**Issue by VinnyHu** [thunlp/DSDocRE#2]
你好，在《Denoising Relation Extraction from Document-level Distant Supervision》中  main results里面的DS-BiLSTM* 与 DS-ContextAware* 关于ign F1的数据 与原论文 DocRE 不符，是否写错误了？

**Comment by xcjthu** [comment]
I have reviewed the results recorded in my paper and DocRED. Our results are consistent with theirs. Thanks a lot for your comments!
